include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    missing_return: warning
    no_leading_underscores_for_local_identifiers: ignore
    use_key_in_widget_constructors: false
  language:
    #    strict-casts: true
    #    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - sort_child_properties_last
