include: package:flutter_lints/flutter.yaml

#analyzer:
#  exclude: [build/**]
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false
#
#linter:
#  rules:
#    always_use_package_imports: true
linter:
  rules:
    - sort_child_properties_last
